### ISSUE TITLE
possible ideas and aliases sources

### ISSUE THREAD

**Issue by ccoVeille** [hougesen/mdsf#162]
By creating #161 I found this interesting resources:

I think it's the list of "fenced blockquote" known by GitHub Flavored Markdown 

https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml

**Comment by ccoVeille** [comment]
so if you support `shell`, you can add `zsh`, `bash`, `shell-script`

You might not need this now but it's interesting

https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml#L6533

**Comment by ccoVeille** [comment]
It's fun to look at the https://gh.io/acemodes then as mentionned in the header.

you will find the js code used to highlight them, so you can see their format

**Comment by ccoVeille** [comment]
maybe I should have opened this in discussion :thinking:

**Comment by hougesen** [comment]
> By creating #161 I found this interesting resources:
> 
> I think it's the list of "fenced blockquote" known by GitHub Flavored Markdown
> 
> https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml

Very cool! 😄

**Comment by ccoVeille** [comment]
Other source of inspiration

https://github.com/benwis/femark

**Comment by ccoVeille** [comment]
> maybe I should have opened this in discussion :thinking: 

I opened https://github.com/hougesen/mdsf/discussions/168

**Comment by ccoVeille** [comment]
Closed, let's usetge discussions
