### ISSUE TITLE
Report missing formatter

### ISSUE THREAD

**Issue by ccoVeille** [hougesen/mdsf#167]
Following #158 idea

Another interesting idea could be to be able to report when our code found block code you could have checked/formatted but you couldn't because the parser is not available.

My point is the fact someone may install your tool, but nothing else.

It will launch mdsf on his markdown files, but it will provide nothing.

So maybe, something you could report at the end as a warning.

**Comment by hougesen** [comment]
Missing binaries are actually reported when running with `--debug`. But yes, it should also be shown to the user when running without --debug

![image](https://github.com/hougesen/mdsf/assets/56034786/ad385803-3d36-4e0f-a37a-66c214c6e8d5)

**Comment by hougesen** [comment]
Could be something like this based on your idea from #158 

```
file1.md (unchanged) 1466 ms with 1 missing binaries
file2.md (unchanged) 1466 ms with 2 errors and 4 missing binaries
```

or a sum after

```
file1.md (unchanged) 123ms
file2.md (unchanged) 123ms

Formatted 2 files in 246ms with 2 errors (file2.md) and 4 missing binaries (prettier, just, biome, rustfmt)
```

**Comment by ccoVeille** [comment]
My point  was more about the fact your tool might be unable to format at block because you find no binaries for a format you support.

So, I think you should talk about formatter and not binaries

I mean if you are formatting a shell script and any of beautysh or shfmt is present, it's OK

the issue is when none of these binary is present
