### ISSUE TITLE
add links to competitors

### ISSUE THREAD

**Issue by ccoVeille** [hougesen/mdsf#191]
This tool has some feature in common with you

https://mdformat.readthedocs.io/en/stable/users/plugins.html#code-formatter-plugins

Maybe it could be mentioned in the README.md

I don't know if you knew it and if it was one of your inspiration or not

**Comment by hougesen** [comment]
I was actually not aware of any direct competitors until after the tool was in a working state. 

My initial inspiration came from using [https://github.com/stevearc/conform.nvim](stevearc/conform.nvim), a formatter plugin for neovim, which supports formatting embedded languages using `injected` mode. Formatting each file manually took ages so  I decided to _"steal"_ the idea 😄
