### ISSUE TITLE
consider adding a homebrew tap to provide your tool

### ISSUE THREAD

**Issue by ccoVeille** [hougesen/mdsf#192]
Having a homebrew tap is a good way to make your tool available for people who don't have/want to build it via go install.

https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

[Homebrew](https://brew.sh/) also helps people to get the last version of the tool. 

cargo crate is a good thing, but it requires installing cargo, it's a dev thing.

Some users are inexperienced or lazy, they use homebrew (please note it works perfectly on Linux, I used it)

I tend to install all my tools with homebrew, so I'm notified when they are updated.

**Comment by hougesen** [comment]
Good idea. Making it easier to install is definitely on my todolist. 

Any other package managers that you think it makes sense to add it to?

I  looked into APT, but it seems like that takes some effort (or a custom PPA). 

Building as wasm and distributing it on npm seems pretty straightforward.

**Comment by ccoVeille** [comment]
I would discourage spending time with apt, it's quite a pain.

I feel you should wait for people to ask you to add things.

Your tool is still new. It's more important to spend time in adding features, so you would get more users. They will give you feedback about what they need/expect.

I raised the point of having an homebrew tap. When it will work, you can consider asking homebrew team to add it to the ones available directly.

Homebrew is pretty used, widely among Mac users, but also on Linux (me for example)

**Comment by hougesen** [comment]
I just setup cargo-dist for one of my other projects which automatically publishes to homebrew. I plan on setting it up for mdsf later this week 😄

**Comment by ccoVeille** [comment]
Great, having it via homebrew will help a lot for the tool installations, but also people, including me will be able to easily get the latest version easily
