### ISSUE TITLE
Documentation: add the list of fenced block you support in the README file

### ISSUE THREAD

**Issue by ccoVeille** [hougesen/mdsf#198]
You are supporting a lot of format yet.

The table you maintain and just updated for restructured text parser is good, but I think you should add the list of "fenced block identifiers" (I'm unsure how to call it)

This would help people figure by their own if it's normal this is supported

````markdown
```whatever
```
````

while this one is not

````markdown
```somethingelse
```
````

The only solution right now is to open the code.

Think about sh, bash, shell, console identifiers. You didn't support them all at first.

**Comment by ccoVeille** [comment]
It would allow some people to understand what is supported. It could avoid people thinking your code is not working because they were in fact using a identifier you had no idea that existed.

**Comment by hougesen** [comment]
I was actually thinking about removing the hardcoded languages in the config, and instead letting the user build their config based on arbitrary codeblock languages.

It would of course mean that the typed `formatter <-> language` combinations would have to be removed.

```json
{
  "languages": {
    "whatever": "rustfmt",
    "somethingelse": "gofmt",
    "json": "clang-format",
    "json5": "prettier",
    "jsonc": "biome"
  }
}
```

I am not really sure whether it is a net positive or negative. What do you think?

**Comment by hougesen** [comment]
The existing default formatters for each language would of course be kept, unless overwritten by a config.

**Comment by ccoVeille** [comment]
> I was actually thinking about removing the hardcoded languages in the config, and instead letting the user build their config based on arbitrary codeblock languages.
> 
> It would of course mean that the typed `formatter <-> language` combinations would have to be removed.
> 
> ```json
> {
>   "languages": {
>     "whatever": "rustfmt",
>     "somethingelse": "gofmt",
>     "json": "clang-format",
>     "json5": "prettier",
>     "jsonc": "biome"
>   }
> }
> ```
> 
> I am not really sure whether it is a net positive or negative. What do you think?
> 

I'm OK with that, but I would say you will need to report unknown fenced code black languages at the end as a warning.

Like 

> the following identifiers were found but not fixed, please update config to fix them:
> foo: 5 blocks
> bar: 7 blocks
